import java.io.FileNotFoundException;
import java.io.FileReader;
import java.lang.reflect.Type;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Random;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public static void main(String[] args) throws FileNotFoundException {
BookQuiry book = new BookQuiry("Qutadah","25","dec");
        System.out.println(book);
        FileReader jsonFile = new FileReader("Countact.json");
        Gson gson = new Gson();
//        System.out.println(gson.toJson(book));

        String jsonContact = "{\"author\"=\"'Qutadah'\",\"likes\"=\"25\",\"text\"= \"dec\"" +
                "  }";
        System.out.println(jsonContact);



    }
}
